// DO NOT EDIT. Generated by gitlab.com/accumulatenetwork/accumulate/tools/cmd/gen-types.

/* eslint-disable @typescript-eslint/no-namespace */

export enum ChainType {
  /** Unknown is used when the chain type is not known. */
  Unknown = 0,
  /** Transaction holds transaction hashes. */
  Transaction = 1,
  /** Anchor holds chain anchors. */
  Anchor = 2,
  /** Index indexes other chains. */
  Index = 4,
}

export namespace ChainType {
  export type Args = ChainType | string;

  export function fromObject(obj: Args): ChainType {
    if (typeof obj === "number") return obj;
    return byName(obj);
  }

  export function byName(name: string): ChainType {
    switch (name) {
      case "unknown":
        return ChainType.Unknown;
      case "transaction":
        return ChainType.Transaction;
      case "anchor":
        return ChainType.Anchor;
      case "index":
        return ChainType.Index;
      default:
        throw new Error(`Unknown ChainType '${name}'`);
    }
  }

  export function getName(v: ChainType): string {
    switch (v) {
      case ChainType.Unknown:
        return "unknown";
      case ChainType.Transaction:
        return "transaction";
      case ChainType.Anchor:
        return "anchor";
      case ChainType.Index:
        return "index";
      default:
        throw new Error(`Unknown ChainType ${v}`);
    }
  }
}
