import { Status } from ".";

// DO NOT EDIT. Generated by gitlab.com/accumulatenetwork/accumulate/tools/cmd/gen-types.

/* eslint-disable @typescript-eslint/no-namespace */
/* eslint-disable @typescript-eslint/no-empty-function */
/* eslint-disable @typescript-eslint/no-unused-vars */

export namespace CallSite {
  export type Args = {
    funcName: string;
    file: string;
    line: number;
  };
}
export class CallSite {
  public funcName: string;
  public file: string;
  public line: number;

  constructor(args: CallSite.Args) {
    this.funcName = args.funcName;
    this.file = args.file;
    this.line = args.line;
  }

  asObject() {
    return {
      funcName: this.funcName,
      file: this.file,
      line: this.line,
    };
  }
}

export namespace Error {
  export type Args = {
    message: string;
    code: Status.Args;
    cause: Error | Error.Args;
    callStack: (CallSite | CallSite.Args)[];
  };
}
export class Error {
  public message: string;
  public code: Status;
  public cause: Error;
  public callStack: CallSite[];

  constructor(args: Error.Args) {
    this.message = args.message;
    this.code = Status.fromObject(args.code);
    this.cause = args.cause instanceof Error ? args.cause : new Error(args.cause);
    this.callStack = args.callStack.map((v) => (v instanceof CallSite ? v : new CallSite(v)));
  }

  asObject() {
    return {
      message: this.message,
      code: this.code.toString(),
      cause: this.cause.asObject(),
      callStack: this.callStack?.map((v) => v.asObject()),
    };
  }
}
