import { ChainType, MerkleState } from ".";

// DO NOT EDIT. Generated by gitlab.com/accumulatenetwork/accumulate/tools/cmd/gen-types.

export class Receipt {
  public start: Uint8Array;
  public startIndex: number;
  public end: Uint8Array;
  public endIndex: number;
  public anchor: Uint8Array;
  public entries: ReceiptEntry[];

  asObject() {
    return {
      start: Buffer.from(this.start).toString("hex"),
      startIndex: this.startIndex,
      end: Buffer.from(this.end).toString("hex"),
      endIndex: this.endIndex,
      anchor: Buffer.from(this.anchor).toString("hex"),
      entries: this.entries?.map((v) => v.asObject()),
    };
  }
}

export class ReceiptEntry {
  public right: boolean;
  public hash: Uint8Array;

  asObject() {
    return {
      right: this.right,
      hash: Buffer.from(this.hash).toString("hex"),
    };
  }
}

export class ReceiptList {
  public merkleState: MerkleState;
  public elements: Uint8Array[];
  public receipt: Receipt;
  public continuedReceipt: Receipt;

  asObject() {
    return {
      merkleState: this.merkleState.asObject(),
      elements: this.elements?.map((v) => Buffer.from(v).toString("hex")),
      receipt: this.receipt.asObject(),
      continuedReceipt: this.continuedReceipt.asObject(),
    };
  }
}

export class Snapshot {
  public name: string;
  public type: ChainType;
  public markPower: number;
  public head: MerkleState;
  public markPoints: MerkleState[];

  asObject() {
    return {
      name: this.name,
      type: this.type.toString(),
      markPower: this.markPower,
      head: this.head.asObject(),
      markPoints: this.markPoints?.map((v) => v.asObject()),
    };
  }
}
