// DO NOT EDIT. Generated by gitlab.com/accumulatenetwork/accumulate/tools/cmd/gen-types.

/* eslint-disable @typescript-eslint/no-namespace */

export enum Status {
  /** OK means the request completed successfully. */
  OK = 200,
  /** Delivered means the transaction has been delivered. */
  Delivered = 201,
  /** Pending means the transaction is pending. */
  Pending = 202,
  /** Remote means the transaction is a local reference to a remote. */
  Remote = 203,
  /** WrongPartition means the requested resource is assigned to a different network partition. */
  WrongPartition = 301,
  /** BadRequest means the request was invalid. */
  BadRequest = 400,
  /** Unauthenticated means the signature could not be validated. */
  Unauthenticated = 401,
  /** InsufficientCredits means the signer does not have sufficient credits to execute the transaction. */
  InsufficientCredits = 402,
  /** Unauthorized means the signer is not authorized to sign the transaction. */
  Unauthorized = 403,
  /** NotFound means a record could not be found. */
  NotFound = 404,
  /** NotAllowed means the requested action could not be performed. */
  NotAllowed = 405,
  /** Conflict means the request failed due to a conflict. */
  Conflict = 409,
  /** BadSignerVersion means the signer version does not match. */
  BadSignerVersion = 411,
  /** BadTimestamp means the timestamp is invalid. */
  BadTimestamp = 412,
  /** BadUrlLength means the url length is too big. */
  BadUrlLength = 413,
  /** IncompleteChain means the chain does not include the full history. */
  IncompleteChain = 414,
  /** InsufficientBalance means the account balance is insufficient to satisfy the request. */
  InsufficientBalance = 415,
  /** InternalError means an internal error occurred. */
  InternalError = 500,
  /** UnknownError means an unknown error occurred. */
  UnknownError = 501,
  /** EncodingError means encoding or decoding failed. */
  EncodingError = 502,
  /** FatalError means something has gone seriously wrong. */
  FatalError = 503,
  /** NotReady means the receiver is not ready to satisfy the request. */
  NotReady = 504,
  /** WrongType means the record is not the expected type. */
  WrongType = 505,
  /** NoPeer means the receiver cannot find a peer to satisfy the request. */
  NoPeer = 506,
  /** PeerMisbehaved means a peer behaved incorrectly. */
  PeerMisbehaved = 507,
}

export namespace Status {
  export type Args = Status | string;

  export function fromObject(obj: Args): Status {
    if (typeof obj === "number") return obj;
    return byName(obj);
  }

  export function byName(name: string): Status {
    switch (name) {
      case "ok":
        return Status.OK;
      case "delivered":
        return Status.Delivered;
      case "pending":
        return Status.Pending;
      case "remote":
        return Status.Remote;
      case "wrongpartition":
        return Status.WrongPartition;
      case "badrequest":
        return Status.BadRequest;
      case "unauthenticated":
        return Status.Unauthenticated;
      case "insufficientcredits":
        return Status.InsufficientCredits;
      case "unauthorized":
        return Status.Unauthorized;
      case "notfound":
        return Status.NotFound;
      case "notallowed":
        return Status.NotAllowed;
      case "conflict":
        return Status.Conflict;
      case "badsignerversion":
        return Status.BadSignerVersion;
      case "badtimestamp":
        return Status.BadTimestamp;
      case "badurllength":
        return Status.BadUrlLength;
      case "incompletechain":
        return Status.IncompleteChain;
      case "insufficientbalance":
        return Status.InsufficientBalance;
      case "internalerror":
        return Status.InternalError;
      case "unknownerror":
        return Status.UnknownError;
      case "encodingerror":
        return Status.EncodingError;
      case "fatalerror":
        return Status.FatalError;
      case "notready":
        return Status.NotReady;
      case "wrongtype":
        return Status.WrongType;
      case "nopeer":
        return Status.NoPeer;
      case "peermisbehaved":
        return Status.PeerMisbehaved;
      default:
        throw new Error(`Unknown Status '${name}'`);
    }
  }

  export function getName(v: Status) {
    switch (v) {
      case Status.OK:
        return "ok";
      case Status.Delivered:
        return "delivered";
      case Status.Pending:
        return "pending";
      case Status.Remote:
        return "remote";
      case Status.WrongPartition:
        return "wrongPartition";
      case Status.BadRequest:
        return "badRequest";
      case Status.Unauthenticated:
        return "unauthenticated";
      case Status.InsufficientCredits:
        return "insufficientCredits";
      case Status.Unauthorized:
        return "unauthorized";
      case Status.NotFound:
        return "notFound";
      case Status.NotAllowed:
        return "notAllowed";
      case Status.Conflict:
        return "conflict";
      case Status.BadSignerVersion:
        return "badSignerVersion";
      case Status.BadTimestamp:
        return "badTimestamp";
      case Status.BadUrlLength:
        return "badUrlLength";
      case Status.IncompleteChain:
        return "incompleteChain";
      case Status.InsufficientBalance:
        return "insufficientBalance";
      case Status.InternalError:
        return "internalError";
      case Status.UnknownError:
        return "unknownError";
      case Status.EncodingError:
        return "encodingError";
      case Status.FatalError:
        return "fatalError";
      case Status.NotReady:
        return "notReady";
      case Status.WrongType:
        return "wrongType";
      case Status.NoPeer:
        return "noPeer";
      case Status.PeerMisbehaved:
        return "peerMisbehaved";
      default:
        throw new Error(`Unknown Status ${v}`);
    }
  }
}
