// DO NOT EDIT. Generated by gitlab.com/accumulatenetwork/accumulate/tools/cmd/gen-types.

/* eslint-disable @typescript-eslint/no-namespace */

export enum EventType {
  /** Error . */
  Error = 1,
  /** Block . */
  Block = 2,
  /** Globals . */
  Globals = 3,
}

export type EventTypeArgs = EventType | string;

/** @ignore */
export namespace EventType {
  export function fromObject(obj: EventTypeArgs): EventType {
    if (typeof obj === "number") return obj;
    return byName(obj);
  }

  export function byName(name: string): EventType {
    switch (name.toLowerCase()) {
      case "error":
        return EventType.Error;
      case "block":
        return EventType.Block;
      case "globals":
        return EventType.Globals;
      default:
        throw new Error(`Unknown EventType '${name}'`);
    }
  }

  export function getName(v: EventType) {
    switch (v) {
      case EventType.Error:
        return "error";
      case EventType.Block:
        return "block";
      case EventType.Globals:
        return "globals";
      default:
        throw new Error(`Unknown EventType ${v}`);
    }
  }
}

export enum QueryType {
  /** Default . */
  Default = 0,
  /** Chain . */
  Chain = 1,
  /** Data . */
  Data = 2,
  /** Directory . */
  Directory = 3,
  /** Pending . */
  Pending = 4,
  /** Block . */
  Block = 5,
  /** AnchorSearch . */
  AnchorSearch = 16,
  /** PublicKeySearch . */
  PublicKeySearch = 17,
  /** PublicKeyHashSearch . */
  PublicKeyHashSearch = 18,
  /** DelegateSearch . */
  DelegateSearch = 19,
  /** MessageHashSearch . */
  MessageHashSearch = 20,
}

export type QueryTypeArgs = QueryType | string;

/** @ignore */
export namespace QueryType {
  export function fromObject(obj: QueryTypeArgs): QueryType {
    if (typeof obj === "number") return obj;
    return byName(obj);
  }

  export function byName(name: string): QueryType {
    switch (name.toLowerCase()) {
      case "default":
        return QueryType.Default;
      case "chain":
        return QueryType.Chain;
      case "data":
        return QueryType.Data;
      case "directory":
        return QueryType.Directory;
      case "pending":
        return QueryType.Pending;
      case "block":
        return QueryType.Block;
      case "anchorsearch":
        return QueryType.AnchorSearch;
      case "publickeysearch":
        return QueryType.PublicKeySearch;
      case "publickeyhashsearch":
        return QueryType.PublicKeyHashSearch;
      case "delegatesearch":
        return QueryType.DelegateSearch;
      case "messagehashsearch":
        return QueryType.MessageHashSearch;
      default:
        throw new Error(`Unknown QueryType '${name}'`);
    }
  }

  export function getName(v: QueryType) {
    switch (v) {
      case QueryType.Default:
        return "default";
      case QueryType.Chain:
        return "chain";
      case QueryType.Data:
        return "data";
      case QueryType.Directory:
        return "directory";
      case QueryType.Pending:
        return "pending";
      case QueryType.Block:
        return "block";
      case QueryType.AnchorSearch:
        return "anchorSearch";
      case QueryType.PublicKeySearch:
        return "publicKeySearch";
      case QueryType.PublicKeyHashSearch:
        return "publicKeyHashSearch";
      case QueryType.DelegateSearch:
        return "delegateSearch";
      case QueryType.MessageHashSearch:
        return "messageHashSearch";
      default:
        throw new Error(`Unknown QueryType ${v}`);
    }
  }
}

export enum RecordType {
  /** Account . */
  Account = 1,
  /** Chain . */
  Chain = 2,
  /** ChainEntry . */
  ChainEntry = 3,
  /** Key . */
  Key = 4,
  /** Message . */
  Message = 16,
  /** SignatureSet . */
  SignatureSet = 17,
  /** MinorBlock . */
  MinorBlock = 32,
  /** MajorBlock . */
  MajorBlock = 33,
  /** Range . */
  Range = 128,
  /** Url . */
  Url = 129,
  /** TxID . */
  TxID = 130,
  /** IndexEntry . */
  IndexEntry = 131,
}

export type RecordTypeArgs = RecordType | string;

/** @ignore */
export namespace RecordType {
  export function fromObject(obj: RecordTypeArgs): RecordType {
    if (typeof obj === "number") return obj;
    return byName(obj);
  }

  export function byName(name: string): RecordType {
    switch (name.toLowerCase()) {
      case "account":
        return RecordType.Account;
      case "chain":
        return RecordType.Chain;
      case "chainentry":
        return RecordType.ChainEntry;
      case "key":
        return RecordType.Key;
      case "message":
        return RecordType.Message;
      case "signatureset":
        return RecordType.SignatureSet;
      case "minorblock":
        return RecordType.MinorBlock;
      case "majorblock":
        return RecordType.MajorBlock;
      case "range":
        return RecordType.Range;
      case "url":
        return RecordType.Url;
      case "txid":
        return RecordType.TxID;
      case "indexentry":
        return RecordType.IndexEntry;
      default:
        throw new Error(`Unknown RecordType '${name}'`);
    }
  }

  export function getName(v: RecordType) {
    switch (v) {
      case RecordType.Account:
        return "account";
      case RecordType.Chain:
        return "chain";
      case RecordType.ChainEntry:
        return "chainEntry";
      case RecordType.Key:
        return "key";
      case RecordType.Message:
        return "message";
      case RecordType.SignatureSet:
        return "signatureSet";
      case RecordType.MinorBlock:
        return "minorBlock";
      case RecordType.MajorBlock:
        return "majorBlock";
      case RecordType.Range:
        return "range";
      case RecordType.Url:
        return "url";
      case RecordType.TxID:
        return "txID";
      case RecordType.IndexEntry:
        return "indexEntry";
      default:
        throw new Error(`Unknown RecordType ${v}`);
    }
  }
}

export enum ServiceType {
  /** Unknown indicates an unknown service type. */
  Unknown = 0,
  /** Node is the type of [NodeService]. */
  Node = 1,
  /** Consensus is the type of [ConsensusService]. */
  Consensus = 2,
  /** Network is the type of [NetworkService]. */
  Network = 3,
  /** Metrics is the type of [MetricsService]. */
  Metrics = 4,
  /** Query is the type of [Querier]. */
  Query = 5,
  /** Event is the type of [EventService]. */
  Event = 6,
  /** Submit is the type of [Submitter]. */
  Submit = 7,
  /** Validate is the type of [Validator]. */
  Validate = 8,
  /** Faucet is the type of [Faucet]. */
  Faucet = 9,
}

export type ServiceTypeArgs = ServiceType | string;

/** @ignore */
export namespace ServiceType {
  export function fromObject(obj: ServiceTypeArgs): ServiceType {
    if (typeof obj === "number") return obj;
    return byName(obj);
  }

  export function byName(name: string): ServiceType {
    switch (name.toLowerCase()) {
      case "unknown":
        return ServiceType.Unknown;
      case "node":
        return ServiceType.Node;
      case "consensus":
        return ServiceType.Consensus;
      case "network":
        return ServiceType.Network;
      case "metrics":
        return ServiceType.Metrics;
      case "query":
        return ServiceType.Query;
      case "event":
        return ServiceType.Event;
      case "submit":
        return ServiceType.Submit;
      case "validate":
        return ServiceType.Validate;
      case "faucet":
        return ServiceType.Faucet;
      default:
        throw new Error(`Unknown ServiceType '${name}'`);
    }
  }

  export function getName(v: ServiceType) {
    switch (v) {
      case ServiceType.Unknown:
        return "unknown";
      case ServiceType.Node:
        return "node";
      case ServiceType.Consensus:
        return "consensus";
      case ServiceType.Network:
        return "network";
      case ServiceType.Metrics:
        return "metrics";
      case ServiceType.Query:
        return "query";
      case ServiceType.Event:
        return "event";
      case ServiceType.Submit:
        return "submit";
      case ServiceType.Validate:
        return "validate";
      case ServiceType.Faucet:
        return "faucet";
      default:
        throw new Error(`Unknown ServiceType ${v}`);
    }
  }
}
