// DO NOT EDIT. Generated by gitlab.com/accumulatenetwork/accumulate/tools/cmd/gen-types.

/* eslint-disable @typescript-eslint/no-namespace */

export enum Type {
  /** NodeInfoRequest . */
  NodeInfoRequest = 1,
  /** FindServiceRequest . */
  FindServiceRequest = 2,
  /** ConsensusStatusRequest . */
  ConsensusStatusRequest = 3,
  /** NetworkStatusRequest . */
  NetworkStatusRequest = 4,
  /** MetricsRequest . */
  MetricsRequest = 5,
  /** QueryRequest . */
  QueryRequest = 6,
  /** SubmitRequest . */
  SubmitRequest = 7,
  /** ValidateRequest . */
  ValidateRequest = 8,
  /** SubscribeRequest . */
  SubscribeRequest = 9,
  /** FaucetRequest . */
  FaucetRequest = 10,
  /** ErrorResponse . */
  ErrorResponse = 32,
  /** NodeInfoResponse . */
  NodeInfoResponse = 33,
  /** FindServiceResponse . */
  FindServiceResponse = 34,
  /** ConsensusStatusResponse . */
  ConsensusStatusResponse = 35,
  /** NetworkStatusResponse . */
  NetworkStatusResponse = 36,
  /** MetricsResponse . */
  MetricsResponse = 37,
  /** RecordResponse . */
  RecordResponse = 38,
  /** SubmitResponse . */
  SubmitResponse = 39,
  /** ValidateResponse . */
  ValidateResponse = 40,
  /** SubscribeResponse . */
  SubscribeResponse = 41,
  /** FaucetResponse . */
  FaucetResponse = 42,
  /** Event . */
  Event = 64,
  /** PrivateSequenceRequest . */
  PrivateSequenceRequest = 128,
  /** PrivateSequenceResponse . */
  PrivateSequenceResponse = 129,
  /** Addressed . */
  Addressed = 255,
}

export type TypeArgs = Type | string;

/** @ignore */
export namespace Type {
  export function fromObject(obj: TypeArgs): Type {
    if (typeof obj === "number") return obj;
    return byName(obj);
  }

  export function byName(name: string): Type {
    switch (name.toLowerCase()) {
      case "nodeinforequest":
        return Type.NodeInfoRequest;
      case "findservicerequest":
        return Type.FindServiceRequest;
      case "consensusstatusrequest":
        return Type.ConsensusStatusRequest;
      case "networkstatusrequest":
        return Type.NetworkStatusRequest;
      case "metricsrequest":
        return Type.MetricsRequest;
      case "queryrequest":
        return Type.QueryRequest;
      case "submitrequest":
        return Type.SubmitRequest;
      case "validaterequest":
        return Type.ValidateRequest;
      case "subscriberequest":
        return Type.SubscribeRequest;
      case "faucetrequest":
        return Type.FaucetRequest;
      case "errorresponse":
        return Type.ErrorResponse;
      case "nodeinforesponse":
        return Type.NodeInfoResponse;
      case "findserviceresponse":
        return Type.FindServiceResponse;
      case "consensusstatusresponse":
        return Type.ConsensusStatusResponse;
      case "networkstatusresponse":
        return Type.NetworkStatusResponse;
      case "metricsresponse":
        return Type.MetricsResponse;
      case "recordresponse":
        return Type.RecordResponse;
      case "submitresponse":
        return Type.SubmitResponse;
      case "validateresponse":
        return Type.ValidateResponse;
      case "subscriberesponse":
        return Type.SubscribeResponse;
      case "faucetresponse":
        return Type.FaucetResponse;
      case "event":
        return Type.Event;
      case "privatesequencerequest":
        return Type.PrivateSequenceRequest;
      case "privatesequenceresponse":
        return Type.PrivateSequenceResponse;
      case "addressed":
        return Type.Addressed;
      default:
        throw new Error(`Unknown Type '${name}'`);
    }
  }

  export function getName(v: Type) {
    switch (v) {
      case Type.NodeInfoRequest:
        return "nodeInfoRequest";
      case Type.FindServiceRequest:
        return "findServiceRequest";
      case Type.ConsensusStatusRequest:
        return "consensusStatusRequest";
      case Type.NetworkStatusRequest:
        return "networkStatusRequest";
      case Type.MetricsRequest:
        return "metricsRequest";
      case Type.QueryRequest:
        return "queryRequest";
      case Type.SubmitRequest:
        return "submitRequest";
      case Type.ValidateRequest:
        return "validateRequest";
      case Type.SubscribeRequest:
        return "subscribeRequest";
      case Type.FaucetRequest:
        return "faucetRequest";
      case Type.ErrorResponse:
        return "errorResponse";
      case Type.NodeInfoResponse:
        return "nodeInfoResponse";
      case Type.FindServiceResponse:
        return "findServiceResponse";
      case Type.ConsensusStatusResponse:
        return "consensusStatusResponse";
      case Type.NetworkStatusResponse:
        return "networkStatusResponse";
      case Type.MetricsResponse:
        return "metricsResponse";
      case Type.RecordResponse:
        return "recordResponse";
      case Type.SubmitResponse:
        return "submitResponse";
      case Type.ValidateResponse:
        return "validateResponse";
      case Type.SubscribeResponse:
        return "subscribeResponse";
      case Type.FaucetResponse:
        return "faucetResponse";
      case Type.Event:
        return "event";
      case Type.PrivateSequenceRequest:
        return "privateSequenceRequest";
      case Type.PrivateSequenceResponse:
        return "privateSequenceResponse";
      case Type.Addressed:
        return "addressed";
      default:
        throw new Error(`Unknown Type ${v}`);
    }
  }
}
