// DO NOT EDIT. Generated by generate-sdk.sh.

/* eslint-disable @typescript-eslint/no-namespace */

export enum AccountType {
  /** Unknown represents an unknown account type. */
  Unknown = 0,
  /** Anchor is one or more Merkle DAG anchors. */
  Anchor = 1,
  /** Identity is an Identity account, aka an ADI. */
  Identity = 2,
  /** TokenIssuer is a Token Issuer account. */
  TokenIssuer = 3,
  /** TokenAccount is an ADI Token Account. */
  TokenAccount = 4,
  /** LiteTokenAccount is a Lite Token Account. */
  LiteTokenAccount = 5,
  /** Transaction is a completed transaction. */
  Transaction = 7,
  /** PendingTransaction is a pending transaction. */
  PendingTransaction = 8,
  /** KeyPage is a Key Page account. */
  KeyPage = 9,
  /** KeyBook is a Key Book account. */
  KeyBook = 10,
  /** DataAccount is an ADI Data Account. */
  DataAccount = 11,
  /** LiteDataAccount is a Lite Data Account. */
  LiteDataAccount = 12,
  /** InternalLedger is a ledger that tracks the state of internal operations. */
  InternalLedger = 14,
}

export namespace AccountType {
  export function byName(name: string): AccountType {
    switch (name) {
      case "unknown":
        return AccountType.Unknown;
      case "anchor":
        return AccountType.Anchor;
      case "identity":
        return AccountType.Identity;
      case "tokenIssuer":
        return AccountType.TokenIssuer;
      case "token":
        return AccountType.TokenIssuer;
      case "tokenAccount":
        return AccountType.TokenAccount;
      case "liteTokenAccount":
        return AccountType.LiteTokenAccount;
      case "transaction":
        return AccountType.Transaction;
      case "pendingTransaction":
        return AccountType.PendingTransaction;
      case "keyPage":
        return AccountType.KeyPage;
      case "keyBook":
        return AccountType.KeyBook;
      case "dataAccount":
        return AccountType.DataAccount;
      case "liteDataAccount":
        return AccountType.LiteDataAccount;
      case "internalLedger":
        return AccountType.InternalLedger;
      default:
        throw new Error(`Unknown AccountType '${name}'`);
    }
  }
}

export enum ChainType {
  /** Unknown is used when the chain type is not known. */
  Unknown = 0,
  /** Transaction holds transaction hashes. */
  Transaction = 1,
  /** Anchor holds chain anchors. */
  Anchor = 2,
  /** Data holds data entry hashes. */
  Data = 3,
}

export namespace ChainType {
  export function byName(name: string): ChainType {
    switch (name) {
      case "unknown":
        return ChainType.Unknown;
      case "transaction":
        return ChainType.Transaction;
      case "anchor":
        return ChainType.Anchor;
      case "data":
        return ChainType.Data;
      default:
        throw new Error(`Unknown ChainType '${name}'`);
    }
  }
}

export enum KeyPageOperation {
  /** Unknown is used when the key page operation is not known. */
  Unknown = 0,
  /** Update replaces a key in the page with a new key. */
  Update = 1,
  /** Remove removes a key from the page. */
  Remove = 2,
  /** Add adds a key to the page. */
  Add = 3,
  /** SetThreshold sets the signing threshold (the M of "M of N" signatures required). */
  SetThreshold = 4,
}

export namespace KeyPageOperation {
  export function byName(name: string): KeyPageOperation {
    switch (name) {
      case "unknown":
        return KeyPageOperation.Unknown;
      case "update":
        return KeyPageOperation.Update;
      case "remove":
        return KeyPageOperation.Remove;
      case "add":
        return KeyPageOperation.Add;
      case "setThreshold":
        return KeyPageOperation.SetThreshold;
      default:
        throw new Error(`Unknown KeyPageOperation '${name}'`);
    }
  }
}

export enum ObjectType {
  /** Unknown is used when the object type is not known. */
  Unknown = 0,
  /** Account represents an account object. */
  Account = 1,
  /** Transaction represents a transaction object. */
  Transaction = 2,
}

export namespace ObjectType {
  export function byName(name: string): ObjectType {
    switch (name) {
      case "unknown":
        return ObjectType.Unknown;
      case "account":
        return ObjectType.Account;
      case "transaction":
        return ObjectType.Transaction;
      default:
        throw new Error(`Unknown ObjectType '${name}'`);
    }
  }
}

export enum TransactionMax {
  /** User is the highest number reserved for user transactions. */
  User = 47,
  /** Synthetic is the highest number reserved for synthetic transactions. */
  Synthetic = 95,
  /** Internal is the highest number reserved for internal transactions. */
  Internal = 255,
}

export namespace TransactionMax {
  export function byName(name: string): TransactionMax {
    switch (name) {
      case "user":
        return TransactionMax.User;
      case "synthetic":
        return TransactionMax.Synthetic;
      case "internal":
        return TransactionMax.Internal;
      default:
        throw new Error(`Unknown TransactionMax '${name}'`);
    }
  }
}

export enum TransactionType {
  /** Unknown represents an unknown transaction type. */
  Unknown = 0,
  /** CreateIdentity creates an ADI, which produces a synthetic chain. */
  CreateIdentity = 1,
  /** CreateTokenAccount creates an ADI token account, which produces a synthetic chain create transaction. */
  CreateTokenAccount = 2,
  /** SendTokens transfers tokens between token accounts, which produces a synthetic deposit tokens transaction. */
  SendTokens = 3,
  /** CreateDataAccount creates an ADI Data Account, which produces a synthetic chain create transaction. */
  CreateDataAccount = 4,
  /** WriteData writes data to an ADI Data Account, which *does not* produce a synthetic transaction. */
  WriteData = 5,
  /** WriteDataTo writes data to a Lite Data Account, which produces a synthetic write data transaction. */
  WriteDataTo = 6,
  /** AcmeFaucet produces a synthetic deposit tokens transaction that deposits ACME tokens into a lite token account. */
  AcmeFaucet = 7,
  /** CreateToken creates a token issuer, which produces a synthetic chain create transaction. */
  CreateToken = 8,
  /** IssueTokens issues tokens to a token account, which produces a synthetic token deposit transaction. */
  IssueTokens = 9,
  /** BurnTokens burns tokens from a token account, which produces a synthetic burn tokens transaction. */
  BurnTokens = 10,
  /** CreateKeyPage creates a key page, which produces a synthetic chain create transaction. */
  CreateKeyPage = 12,
  /** CreateKeyBook creates a key book, which produces a synthetic chain create transaction. */
  CreateKeyBook = 13,
  /** AddCredits converts ACME tokens to credits, which produces a synthetic deposit credits transaction. */
  AddCredits = 14,
  /** UpdateKeyPage adds, removes, or updates keys in a key page, which *does not* produce a synthetic transaction. */
  UpdateKeyPage = 15,
  /** UpdateManager updates manager for the existing chain. */
  UpdateManager = 16,
  /** RemoveManager remove manager from existing chain. */
  RemoveManager = 17,
  /** SignPending is used to sign a pending transaction. */
  SignPending = 48,
  /** SyntheticCreateChain creates or updates chains. */
  SyntheticCreateChain = 49,
  /** SyntheticWriteData writes data to a data account. */
  SyntheticWriteData = 50,
  /** SyntheticDepositTokens deposits tokens into token accounts. */
  SyntheticDepositTokens = 51,
  /** SyntheticAnchor anchors one network to another. */
  SyntheticAnchor = 52,
  /** SyntheticDepositCredits deposits credits into a credit holder. */
  SyntheticDepositCredits = 53,
  /** SyntheticBurnTokens returns tokens to a token issuer's pool of issuable tokens. */
  SyntheticBurnTokens = 54,
  /** SyntheticMirror mirrors records from one network to another. */
  SyntheticMirror = 56,
  /** SegWitDataEntry is a surrogate transaction segregated witness for a WriteData transaction. */
  SegWitDataEntry = 57,
  /** InternalGenesis initializes system chains. */
  InternalGenesis = 96,
  /** InternalSendTransactions reserved for internal send. */
  InternalSendTransactions = 97,
  /** InternalTransactionsSigned notifies the executor of synthetic transactions that have been signed. */
  InternalTransactionsSigned = 98,
  /** InternalTransactionsSent notifies the executor of synthetic transactions that have been sent. */
  InternalTransactionsSent = 99,
}

export namespace TransactionType {
  export function byName(name: string): TransactionType {
    switch (name) {
      case "unknown":
        return TransactionType.Unknown;
      case "createIdentity":
        return TransactionType.CreateIdentity;
      case "createTokenAccount":
        return TransactionType.CreateTokenAccount;
      case "sendTokens":
        return TransactionType.SendTokens;
      case "createDataAccount":
        return TransactionType.CreateDataAccount;
      case "writeData":
        return TransactionType.WriteData;
      case "writeDataTo":
        return TransactionType.WriteDataTo;
      case "acmeFaucet":
        return TransactionType.AcmeFaucet;
      case "createToken":
        return TransactionType.CreateToken;
      case "issueTokens":
        return TransactionType.IssueTokens;
      case "burnTokens":
        return TransactionType.BurnTokens;
      case "createKeyPage":
        return TransactionType.CreateKeyPage;
      case "createKeyBook":
        return TransactionType.CreateKeyBook;
      case "addCredits":
        return TransactionType.AddCredits;
      case "updateKeyPage":
        return TransactionType.UpdateKeyPage;
      case "updateManager":
        return TransactionType.UpdateManager;
      case "removeManager":
        return TransactionType.RemoveManager;
      case "signPending":
        return TransactionType.SignPending;
      case "syntheticCreateChain":
        return TransactionType.SyntheticCreateChain;
      case "syntheticWriteData":
        return TransactionType.SyntheticWriteData;
      case "syntheticDepositTokens":
        return TransactionType.SyntheticDepositTokens;
      case "syntheticAnchor":
        return TransactionType.SyntheticAnchor;
      case "syntheticDepositCredits":
        return TransactionType.SyntheticDepositCredits;
      case "syntheticBurnTokens":
        return TransactionType.SyntheticBurnTokens;
      case "syntheticMirror":
        return TransactionType.SyntheticMirror;
      case "segWitDataEntry":
        return TransactionType.SegWitDataEntry;
      case "internalGenesis":
        return TransactionType.InternalGenesis;
      case "internalSendTransactions":
        return TransactionType.InternalSendTransactions;
      case "internalTransactionsSigned":
        return TransactionType.InternalTransactionsSigned;
      case "internalTransactionsSent":
        return TransactionType.InternalTransactionsSent;
      default:
        throw new Error(`Unknown TransactionType '${name}'`);
    }
  }
}
