// DO NOT EDIT. Generated by generate-sdk.sh.

/* eslint-disable @typescript-eslint/no-namespace */

export enum KeyPageOperation {
  /** Unknown is used when the key page operation is not known. */
  Unknown = 0,
  /** Update replaces a key in the page with a new key. */
  Update = 1,
  /** Remove removes a key from the page. */
  Remove = 2,
  /** Add adds a key to the page. */
  Add = 3,
  /** SetThreshold sets the signing threshold (the M of "M of N" signatures required). */
  SetThreshold = 4,
}

export namespace KeyPageOperation {
  export function byName(name: string): KeyPageOperation {
    switch (name) {
      case "unknown":
        return KeyPageOperation.Unknown;
      case "update":
        return KeyPageOperation.Update;
      case "remove":
        return KeyPageOperation.Remove;
      case "add":
        return KeyPageOperation.Add;
      case "setThreshold":
        return KeyPageOperation.SetThreshold;
      default:
        throw new Error(`Unknown KeyPageOperation '${name}'`);
    }
  }
}

export enum SignatureType {
  /** Unknown is used when the signature type is not known. */
  Unknown = 0,
  /** LegacyED25519 represents a legacy ED25519 signature. */
  LegacyED25519 = 1,
  /** ED25519 represents an ED25519 signature. */
  ED25519 = 2,
  /** RCD1 represents an RCD1 signature. */
  RCD1 = 3,
  /** Receipt represents a Merkle tree receipt. */
  Receipt = 4,
  /** Synthetic is used when sending synthetic transactions. */
  Synthetic = 5,
  /** Internal is used when executing transactions internally. */
  Internal = 6,
}

export namespace SignatureType {
  export function byName(name: string): SignatureType {
    switch (name) {
      case "unknown":
        return SignatureType.Unknown;
      case "legacyED25519":
        return SignatureType.LegacyED25519;
      case "eD25519":
        return SignatureType.ED25519;
      case "rCD1":
        return SignatureType.RCD1;
      case "receipt":
        return SignatureType.Receipt;
      case "synthetic":
        return SignatureType.Synthetic;
      case "internal":
        return SignatureType.Internal;
      default:
        throw new Error(`Unknown SignatureType '${name}'`);
    }
  }
}

export enum TransactionType {
  /** Unknown represents an unknown transaction type. */
  Unknown = 0,
  /** CreateIdentity creates an ADI, which produces a synthetic chain. */
  CreateIdentity = 1,
  /** CreateTokenAccount creates an ADI token account, which produces a synthetic chain create transaction. */
  CreateTokenAccount = 2,
  /** SendTokens transfers tokens between token accounts, which produces a synthetic deposit tokens transaction. */
  SendTokens = 3,
  /** CreateDataAccount creates an ADI Data Account, which produces a synthetic chain create transaction. */
  CreateDataAccount = 4,
  /** WriteData writes data to an ADI Data Account, which *does not* produce a synthetic transaction. */
  WriteData = 5,
  /** WriteDataTo writes data to a Lite Data Account, which produces a synthetic write data transaction. */
  WriteDataTo = 6,
  /** AcmeFaucet produces a synthetic deposit tokens transaction that deposits ACME tokens into a lite token account. */
  AcmeFaucet = 7,
  /** CreateToken creates a token issuer, which produces a synthetic chain create transaction. */
  CreateToken = 8,
  /** IssueTokens issues tokens to a token account, which produces a synthetic token deposit transaction. */
  IssueTokens = 9,
  /** BurnTokens burns tokens from a token account, which produces a synthetic burn tokens transaction. */
  BurnTokens = 10,
  /** CreateKeyPage creates a key page, which produces a synthetic chain create transaction. */
  CreateKeyPage = 12,
  /** CreateKeyBook creates a key book, which produces a synthetic chain create transaction. */
  CreateKeyBook = 13,
  /** AddCredits converts ACME tokens to credits, which produces a synthetic deposit credits transaction. */
  AddCredits = 14,
  /** UpdateKeyPage adds, removes, or updates keys in a key page, which *does not* produce a synthetic transaction. */
  UpdateKeyPage = 15,
  /** UpdateManager updates manager for the existing chain. */
  UpdateManager = 16,
  /** RemoveManager remove manager from existing chain. */
  RemoveManager = 17,
  /** AddValidator add a validator. */
  AddValidator = 18,
  /** RemoveValidator remove a validator. */
  RemoveValidator = 19,
  /** UpdateValidatorKey update a validator key. */
  UpdateValidatorKey = 20,
  /** SignPending is used to sign a pending transaction. */
  SignPending = 48,
  /** SyntheticCreateChain creates or updates chains. */
  SyntheticCreateChain = 49,
  /** SyntheticWriteData writes data to a data account. */
  SyntheticWriteData = 50,
  /** SyntheticDepositTokens deposits tokens into token accounts. */
  SyntheticDepositTokens = 51,
  /** SyntheticAnchor anchors one network to another. */
  SyntheticAnchor = 52,
  /** SyntheticDepositCredits deposits credits into a credit holder. */
  SyntheticDepositCredits = 53,
  /** SyntheticBurnTokens returns tokens to a token issuer's pool of issuable tokens. */
  SyntheticBurnTokens = 54,
  /** SyntheticMirror mirrors records from one network to another. */
  SyntheticMirror = 56,
  /** SegWitDataEntry is a surrogate transaction segregated witness for a WriteData transaction. */
  SegWitDataEntry = 57,
  /** InternalGenesis initializes system chains. */
  InternalGenesis = 96,
  /** InternalSendTransactions reserved for internal send. */
  InternalSendTransactions = 97,
  /** InternalTransactionsSigned notifies the executor of synthetic transactions that have been signed. */
  InternalTransactionsSigned = 98,
  /** InternalTransactionsSent notifies the executor of synthetic transactions that have been sent. */
  InternalTransactionsSent = 99,
}

export namespace TransactionType {
  export function byName(name: string): TransactionType {
    switch (name) {
      case "unknown":
        return TransactionType.Unknown;
      case "createIdentity":
        return TransactionType.CreateIdentity;
      case "createTokenAccount":
        return TransactionType.CreateTokenAccount;
      case "sendTokens":
        return TransactionType.SendTokens;
      case "createDataAccount":
        return TransactionType.CreateDataAccount;
      case "writeData":
        return TransactionType.WriteData;
      case "writeDataTo":
        return TransactionType.WriteDataTo;
      case "acmeFaucet":
        return TransactionType.AcmeFaucet;
      case "createToken":
        return TransactionType.CreateToken;
      case "issueTokens":
        return TransactionType.IssueTokens;
      case "burnTokens":
        return TransactionType.BurnTokens;
      case "createKeyPage":
        return TransactionType.CreateKeyPage;
      case "createKeyBook":
        return TransactionType.CreateKeyBook;
      case "addCredits":
        return TransactionType.AddCredits;
      case "updateKeyPage":
        return TransactionType.UpdateKeyPage;
      case "updateManager":
        return TransactionType.UpdateManager;
      case "removeManager":
        return TransactionType.RemoveManager;
      case "addValidator":
        return TransactionType.AddValidator;
      case "removeValidator":
        return TransactionType.RemoveValidator;
      case "updateValidatorKey":
        return TransactionType.UpdateValidatorKey;
      case "signPending":
        return TransactionType.SignPending;
      case "syntheticCreateChain":
        return TransactionType.SyntheticCreateChain;
      case "syntheticWriteData":
        return TransactionType.SyntheticWriteData;
      case "syntheticDepositTokens":
        return TransactionType.SyntheticDepositTokens;
      case "syntheticAnchor":
        return TransactionType.SyntheticAnchor;
      case "syntheticDepositCredits":
        return TransactionType.SyntheticDepositCredits;
      case "syntheticBurnTokens":
        return TransactionType.SyntheticBurnTokens;
      case "syntheticMirror":
        return TransactionType.SyntheticMirror;
      case "segWitDataEntry":
        return TransactionType.SegWitDataEntry;
      case "internalGenesis":
        return TransactionType.InternalGenesis;
      case "internalSendTransactions":
        return TransactionType.InternalSendTransactions;
      case "internalTransactionsSigned":
        return TransactionType.InternalTransactionsSigned;
      case "internalTransactionsSent":
        return TransactionType.InternalTransactionsSent;
      default:
        throw new Error(`Unknown TransactionType '${name}'`);
    }
  }
}
