// DO NOT EDIT. Generated by gitlab.com/accumulatenetwork/accumulate/tools/cmd/gen-types.

/* eslint-disable @typescript-eslint/no-namespace */

export enum BlockFilterMode {
  /** ExcludeNone return all blocks including empty ones. */
  ExcludeNone = 0,
  /** ExcludeEmpty exclude empty blocks. */
  ExcludeEmpty = 1,
}

export namespace BlockFilterMode {
  export type Args = BlockFilterMode | string;

  export function fromObject(obj: Args): BlockFilterMode {
    if (typeof obj === "number") return obj;
    return byName(obj);
  }

  export function byName(name: string): BlockFilterMode {
    switch (name) {
      case "excludenone":
        return BlockFilterMode.ExcludeNone;
      case "excludeempty":
        return BlockFilterMode.ExcludeEmpty;
      default:
        throw new Error(`Unknown BlockFilterMode '${name}'`);
    }
  }
}

export enum TxFetchMode {
  /** Expand expand the full transactions in the result set. */
  Expand = 0,
  /** Ids include the transaction IDs & count in the result set. */
  Ids = 1,
  /** CountOnly only include the transaction count in the result set. */
  CountOnly = 2,
  /** Omit omit all transaction info from the result set. */
  Omit = 3,
}

export namespace TxFetchMode {
  export type Args = TxFetchMode | string;

  export function fromObject(obj: Args): TxFetchMode {
    if (typeof obj === "number") return obj;
    return byName(obj);
  }

  export function byName(name: string): TxFetchMode {
    switch (name) {
      case "expand":
        return TxFetchMode.Expand;
      case "ids":
        return TxFetchMode.Ids;
      case "countonly":
        return TxFetchMode.CountOnly;
      case "omit":
        return TxFetchMode.Omit;
      default:
        throw new Error(`Unknown TxFetchMode '${name}'`);
    }
  }
}
