// DO NOT EDIT. Generated by gitlab.com/accumulatenetwork/accumulate/tools/cmd/gen-types.

/* eslint-disable @typescript-eslint/no-namespace */

export enum MessageType {
  /** Transaction is a transaction. */
  Transaction = 1,
  /** Signature is a signature. */
  Signature = 2,
  /** BadSynthetic is deprecated. */
  BadSynthetic = 3,
  /** BlockAnchor is a block anchor signed by validator. */
  BlockAnchor = 4,
  /** Sequenced is a message that is part of a sequence. */
  Sequenced = 5,
  /** SignatureRequest is a request for additional signatures. */
  SignatureRequest = 6,
  /** CreditPayment is a payment of credits towards a transaction's fee. */
  CreditPayment = 7,
  /** BlockSummary is a summary of a block. */
  BlockSummary = 8,
  /** Synthetic is a message produced by the protocol, requiring proof. */
  Synthetic = 9,
  /** NetworkUpdate is an update to network parameters. */
  NetworkUpdate = 10,
  /** MakeMajorBlock triggers a major block. */
  MakeMajorBlock = 11,
  /** DidUpdateExecutorVersion notifies the DN that a BVN updated the executor version. */
  DidUpdateExecutorVersion = 12,
}

export type MessageTypeArgs = MessageType | string;

/** @ignore */
export namespace MessageType {
  export function fromObject(obj: MessageTypeArgs): MessageType {
    if (typeof obj === "number") return obj;
    return byName(obj);
  }

  export function byName(name: string): MessageType {
    switch (name.toLowerCase()) {
      case "transaction":
        return MessageType.Transaction;
      case "signature":
        return MessageType.Signature;
      case "badsynthetic":
        return MessageType.BadSynthetic;
      case "blockanchor":
        return MessageType.BlockAnchor;
      case "sequenced":
        return MessageType.Sequenced;
      case "signaturerequest":
        return MessageType.SignatureRequest;
      case "creditpayment":
        return MessageType.CreditPayment;
      case "blocksummary":
        return MessageType.BlockSummary;
      case "synthetic":
        return MessageType.Synthetic;
      case "networkupdate":
        return MessageType.NetworkUpdate;
      case "makemajorblock":
        return MessageType.MakeMajorBlock;
      case "didupdateexecutorversion":
        return MessageType.DidUpdateExecutorVersion;
      default:
        throw new Error(`Unknown MessageType '${name}'`);
    }
  }

  export function getName(v: MessageType) {
    switch (v) {
      case MessageType.Transaction:
        return "transaction";
      case MessageType.Signature:
        return "signature";
      case MessageType.BadSynthetic:
        return "badSynthetic";
      case MessageType.BlockAnchor:
        return "blockAnchor";
      case MessageType.Sequenced:
        return "sequenced";
      case MessageType.SignatureRequest:
        return "signatureRequest";
      case MessageType.CreditPayment:
        return "creditPayment";
      case MessageType.BlockSummary:
        return "blockSummary";
      case MessageType.Synthetic:
        return "synthetic";
      case MessageType.NetworkUpdate:
        return "networkUpdate";
      case MessageType.MakeMajorBlock:
        return "makeMajorBlock";
      case MessageType.DidUpdateExecutorVersion:
        return "didUpdateExecutorVersion";
      default:
        throw new Error(`Unknown MessageType ${v}`);
    }
  }
}
