import * as types from ".";

// DO NOT EDIT. Generated by gitlab.com/accumulatenetwork/accumulate/tools/cmd/gen-types.

/* eslint-disable @typescript-eslint/no-namespace */

export type Message =
  | types.BadSyntheticMessage
  | types.BlockAnchor
  | types.CreditPayment
  | types.DidUpdateExecutorVersion
  | types.MakeMajorBlock
  | types.NetworkUpdate
  | types.SequencedMessage
  | types.SignatureMessage
  | types.SignatureRequest
  | types.SyntheticMessage
  | types.TransactionMessage;

export type MessageArgs =
  | types.BadSyntheticMessage
  | types.BadSyntheticMessageArgsWithType
  | types.BlockAnchor
  | types.BlockAnchorArgsWithType
  | types.CreditPayment
  | types.CreditPaymentArgsWithType
  | types.DidUpdateExecutorVersion
  | types.DidUpdateExecutorVersionArgsWithType
  | types.MakeMajorBlock
  | types.MakeMajorBlockArgsWithType
  | types.NetworkUpdate
  | types.NetworkUpdateArgsWithType
  | types.SequencedMessage
  | types.SequencedMessageArgsWithType
  | types.SignatureMessage
  | types.SignatureMessageArgsWithType
  | types.SignatureRequest
  | types.SignatureRequestArgsWithType
  | types.SyntheticMessage
  | types.SyntheticMessageArgsWithType
  | types.TransactionMessage
  | types.TransactionMessageArgsWithType;

/** @ignore */
export namespace Message {
  export function fromObject(obj: MessageArgs): Message {
    if (obj instanceof types.BadSyntheticMessage) return obj;
    if (obj instanceof types.BlockAnchor) return obj;
    if (obj instanceof types.CreditPayment) return obj;
    if (obj instanceof types.DidUpdateExecutorVersion) return obj;
    if (obj instanceof types.MakeMajorBlock) return obj;
    if (obj instanceof types.NetworkUpdate) return obj;
    if (obj instanceof types.SequencedMessage) return obj;
    if (obj instanceof types.SignatureMessage) return obj;
    if (obj instanceof types.SignatureRequest) return obj;
    if (obj instanceof types.SyntheticMessage) return obj;
    if (obj instanceof types.TransactionMessage) return obj;

    switch (obj.type) {
      case types.MessageType.BadSynthetic:
      case "badSynthetic":
        return new types.BadSyntheticMessage(obj);
      case types.MessageType.BlockAnchor:
      case "blockAnchor":
        return new types.BlockAnchor(obj);
      case types.MessageType.CreditPayment:
      case "creditPayment":
        return new types.CreditPayment(obj);
      case types.MessageType.DidUpdateExecutorVersion:
      case "didUpdateExecutorVersion":
        return new types.DidUpdateExecutorVersion(obj);
      case types.MessageType.MakeMajorBlock:
      case "makeMajorBlock":
        return new types.MakeMajorBlock(obj);
      case types.MessageType.NetworkUpdate:
      case "networkUpdate":
        return new types.NetworkUpdate(obj);
      case types.MessageType.Sequenced:
      case "sequenced":
        return new types.SequencedMessage(obj);
      case types.MessageType.Signature:
      case "signature":
        return new types.SignatureMessage(obj);
      case types.MessageType.SignatureRequest:
      case "signatureRequest":
        return new types.SignatureRequest(obj);
      case types.MessageType.Synthetic:
      case "synthetic":
        return new types.SyntheticMessage(obj);
      case types.MessageType.Transaction:
      case "transaction":
        return new types.TransactionMessage(obj);
      default:
        throw new Error(`Unknown message '${(obj as any).type}'`);
    }
  }
}
