// Example 15: Co-Signing to Satisfy an M-of-N Threshold
//
// A signature threshold is satisfied by DISTINCT keys signing the SAME
// transaction. Signing the same body twice does NOT work: the first signature's
// metadata becomes the transaction's `initiator` and is baked into the header, so
// a second independent signature covers a different transaction hash and neither
// copy reaches the threshold.
//
// The flow is: sign once to build an envelope, co-sign that envelope with each
// additional key, then submit ONCE. Submitting between signatures trips replay
// protection on the signature already on chain.
//
// This example builds a 2-of-3 key page and then raises its threshold to 3 -- a
// change that itself requires two signatures. It targets the multisig page
// because a page's own book is its authority; a transaction against a sub-account
// would be authorized by the ADI's DEFAULT book instead and would sit pending.

/**
 * Multi-Signature Setup
 * Generated by Accumulate Studio
 * Network: kermit
 *
 * Install: npm install accumulate-sdk-opendlt
 * Run with: node script.mjs
 */

import {
    Accumulate,
    SmartSigner,
    TxBody,
    Ed25519KeyPair,
    KERMIT_V2,
    KERMIT_V3,
    pollForBalance,
    pollForCredits,
} from "../../src/index.js";

const V2_ENDPOINT = process.env.ACCUMULATE_V2_URL || KERMIT_V2;
const V3_ENDPOINT = process.env.ACCUMULATE_V3_URL || KERMIT_V3;

async function main() {
    const client = Accumulate.custom(V2_ENDPOINT, V3_ENDPOINT);
    const txIds = [];
    try {
        const adi_name = `adi-${Math.floor(Date.now() / 1000)}`;  // Name for your ADI (e.g., 'my-multisig-adi')


        // =========================================================
        // Generate Keys (Signer 1) (GenerateKeys)
        // =========================================================
        const generateKeysSigner_1Kp = Ed25519KeyPair.generate();
        const generateKeysSigner_1Lid = generateKeysSigner_1Kp.deriveLiteIdentityUrl();
        const generateKeysSigner_1Lta = generateKeysSigner_1Kp.deriveLiteTokenAccountUrl();
        const generateKeysSigner_1PubHash = generateKeysSigner_1Kp.publicKeyHashHex();
        console.log("Generated keypair:");
        console.log(`  Lite Identity: ${generateKeysSigner_1Lid}`);
        console.log(`  Lite Token Account: ${generateKeysSigner_1Lta}`);
        console.log(`  Public Key Hash: ${generateKeysSigner_1PubHash}`);


        // =========================================================
        // Request Tokens (Faucet)
        // =========================================================
        console.log("Requesting tokens from faucet...");
        await client.faucet(generateKeysSigner_1Lta, 3, 2000);
        console.log("Faucet request completed");


        // =========================================================
        // Wait for ACME (WaitForBalance)
        // =========================================================
        console.log("Waiting for balance >= 15.00000000...");
        await pollForBalance(client, generateKeysSigner_1Lta, 15.00000000);
        console.log("Balance reached");


        // =========================================================
        // Add Credits (Action: AddCredits)
        // =========================================================
        const addCreditsOracle = await client.getOraclePrice();
        const addCreditsSigner = new SmartSigner(client, generateKeysSigner_1Kp.toKey(), generateKeysSigner_1Lid);
        const addCreditsResult = await addCreditsSigner.signSubmitAndWait(
            generateKeysSigner_1Lta,
            TxBody.addCredits(
                generateKeysSigner_1Lid,
                "1000000000",
                addCreditsOracle,
            ),
        );
        if (addCreditsResult.success) {
            console.log(`AddCredits SUCCESS - TxID: ${addCreditsResult.txid}`);
            if (addCreditsResult.txid) txIds.push(["AddCredits", addCreditsResult.txid]);
        } else {
            console.log(`AddCredits FAILED: ${addCreditsResult.error}`);
        }


        // =========================================================
        // Wait for Credits (WaitForCredits)
        // =========================================================
        console.log("Waiting for credits >= 1000...");
        await pollForCredits(client, generateKeysSigner_1Lid, 1000);
        console.log("Credits reached");


        // =========================================================
        // Create ADI (Action: CreateIdentity)
        // =========================================================
        const createAdiUrl = `acc://${adi_name}.acme`;
        const createAdiSigner = new SmartSigner(client, generateKeysSigner_1Kp.toKey(), generateKeysSigner_1Lid);
        const createAdiResult = await createAdiSigner.signSubmitAndWait(
            generateKeysSigner_1Lta,
            TxBody.createIdentity(
                createAdiUrl,
                `${createAdiUrl}/book`,
                generateKeysSigner_1PubHash,
            ),
        );
        if (createAdiResult.success) {
            console.log(`CreateIdentity SUCCESS - TxID: ${createAdiResult.txid}`);
            if (createAdiResult.txid) txIds.push(["CreateIdentity", createAdiResult.txid]);
        } else {
            console.log(`CreateIdentity FAILED: ${createAdiResult.error}`);
        }


        // =========================================================
        // Credit Key Page (Action: AddCredits)
        // =========================================================
        const creditKeyPageOracle = await client.getOraclePrice();
        const creditKeyPageSigner = new SmartSigner(client, generateKeysSigner_1Kp.toKey(), generateKeysSigner_1Lid);
        const creditKeyPageResult = await creditKeyPageSigner.signSubmitAndWait(
            generateKeysSigner_1Lta,
            TxBody.addCredits(
                `${createAdiUrl}/book/1`,
                "1000000000",
                creditKeyPageOracle,
            ),
        );
        if (creditKeyPageResult.success) {
            console.log(`AddCredits SUCCESS - TxID: ${creditKeyPageResult.txid}`);
            if (creditKeyPageResult.txid) txIds.push(["AddCredits", creditKeyPageResult.txid]);
        } else {
            console.log(`AddCredits FAILED: ${creditKeyPageResult.error}`);
        }


        // =========================================================
        // Wait for Key Page Credits (WaitForCredits)
        // =========================================================
        console.log("Waiting for credits >= 1000...");
        await pollForCredits(client, `${createAdiUrl}/book/1`, 1000);
        console.log("Credits reached");


        // =========================================================
        // Create Multi-Sig Key Book (Action: CreateKeyBook)
        // =========================================================
        const createMultiSigKeyBookUrl = `${createAdiUrl}/multisig-book`;
        console.log(`Multi-sig key book: ${createMultiSigKeyBookUrl}`);
        const createMultiSigKeyBookSigner = new SmartSigner(client, generateKeysSigner_1Kp.toKey(), `${createAdiUrl}/book/1`);
        const createMultiSigKeyBookResult = await createMultiSigKeyBookSigner.signSubmitAndWait(
            createAdiUrl,
            TxBody.createKeyBook(
                `${createAdiUrl}/multisig-book`,
                generateKeysSigner_1PubHash,
            ),
        );
        if (createMultiSigKeyBookResult.success) {
            console.log(`CreateKeyBook SUCCESS - TxID: ${createMultiSigKeyBookResult.txid}`);
            if (createMultiSigKeyBookResult.txid) txIds.push(["CreateKeyBook", createMultiSigKeyBookResult.txid]);
        } else {
            console.log(`CreateKeyBook FAILED: ${createMultiSigKeyBookResult.error}`);
        }


        // =========================================================
        // Credit Multi-Sig Key Page (Action: AddCredits)
        // =========================================================
        const creditMultiSigKeyPageOracle = await client.getOraclePrice();
        const creditMultiSigKeyPageSigner = new SmartSigner(client, generateKeysSigner_1Kp.toKey(), generateKeysSigner_1Lid);
        const creditMultiSigKeyPageResult = await creditMultiSigKeyPageSigner.signSubmitAndWait(
            generateKeysSigner_1Lta,
            TxBody.addCredits(
                `${createAdiUrl}/multisig-book/1`,
                "500000000",
                creditMultiSigKeyPageOracle,
            ),
        );
        if (creditMultiSigKeyPageResult.success) {
            console.log(`AddCredits SUCCESS - TxID: ${creditMultiSigKeyPageResult.txid}`);
            if (creditMultiSigKeyPageResult.txid) txIds.push(["AddCredits", creditMultiSigKeyPageResult.txid]);
        } else {
            console.log(`AddCredits FAILED: ${creditMultiSigKeyPageResult.error}`);
        }


        // =========================================================
        // Wait for Multi-Sig Credits (WaitForCredits)
        // =========================================================
        console.log("Waiting for credits >= 1000...");
        await pollForCredits(client, `${createAdiUrl}/multisig-book/1`, 1000);
        console.log("Credits reached");


        // =========================================================
        // Generate Keys (Signer 2) (GenerateKeys)
        // =========================================================
        const generateKeysSigner_2Kp = Ed25519KeyPair.generate();
        const generateKeysSigner_2Lid = generateKeysSigner_2Kp.deriveLiteIdentityUrl();
        const generateKeysSigner_2Lta = generateKeysSigner_2Kp.deriveLiteTokenAccountUrl();
        const generateKeysSigner_2PubHash = generateKeysSigner_2Kp.publicKeyHashHex();
        console.log("Generated keypair:");
        console.log(`  Lite Identity: ${generateKeysSigner_2Lid}`);
        console.log(`  Lite Token Account: ${generateKeysSigner_2Lta}`);
        console.log(`  Public Key Hash: ${generateKeysSigner_2PubHash}`);


        // =========================================================
        // Add Signer 2 (Action: UpdateKeyPage)
        // =========================================================
        const addSigner_2Signer = new SmartSigner(client, generateKeysSigner_1Kp.toKey(), `${createAdiUrl}/multisig-book/1`);
        const addSigner_2Result = await addSigner_2Signer.signSubmitAndWait(
            `${createAdiUrl}/multisig-book/1`,
            TxBody.updateKeyPageAddKey(generateKeysSigner_2PubHash),
        );
        if (addSigner_2Result.success) {
            console.log(`UpdateKeyPage SUCCESS - TxID: ${addSigner_2Result.txid}`);
            if (addSigner_2Result.txid) txIds.push(["UpdateKeyPage", addSigner_2Result.txid]);
        } else {
            console.log(`UpdateKeyPage FAILED: ${addSigner_2Result.error}`);
        }


        // =========================================================
        // Generate Keys (Signer 3) (GenerateKeys)
        // =========================================================
        const generateKeysSigner_3Kp = Ed25519KeyPair.generate();
        const generateKeysSigner_3Lid = generateKeysSigner_3Kp.deriveLiteIdentityUrl();
        const generateKeysSigner_3Lta = generateKeysSigner_3Kp.deriveLiteTokenAccountUrl();
        const generateKeysSigner_3PubHash = generateKeysSigner_3Kp.publicKeyHashHex();
        console.log("Generated keypair:");
        console.log(`  Lite Identity: ${generateKeysSigner_3Lid}`);
        console.log(`  Lite Token Account: ${generateKeysSigner_3Lta}`);
        console.log(`  Public Key Hash: ${generateKeysSigner_3PubHash}`);


        // =========================================================
        // Add Signer 3 (Action: UpdateKeyPage)
        // =========================================================
        const addSigner_3Signer = new SmartSigner(client, generateKeysSigner_1Kp.toKey(), `${createAdiUrl}/multisig-book/1`);
        const addSigner_3Result = await addSigner_3Signer.signSubmitAndWait(
            `${createAdiUrl}/multisig-book/1`,
            TxBody.updateKeyPageAddKey(generateKeysSigner_3PubHash),
        );
        if (addSigner_3Result.success) {
            console.log(`UpdateKeyPage SUCCESS - TxID: ${addSigner_3Result.txid}`);
            if (addSigner_3Result.txid) txIds.push(["UpdateKeyPage", addSigner_3Result.txid]);
        } else {
            console.log(`UpdateKeyPage FAILED: ${addSigner_3Result.error}`);
        }


        // =========================================================
        // Set Threshold (2 of 3) (Action: UpdateKeyPage)
        // =========================================================
        const setThreshold_2Of_3Signer = new SmartSigner(client, generateKeysSigner_1Kp.toKey(), `${createAdiUrl}/multisig-book/1`);
        const setThreshold_2Of_3Result = await setThreshold_2Of_3Signer.signSubmitAndWait(
            `${createAdiUrl}/multisig-book/1`,
            TxBody.updateKeyPageSetThreshold(2),
        );
        if (setThreshold_2Of_3Result.success) {
            console.log(`UpdateKeyPage SUCCESS - TxID: ${setThreshold_2Of_3Result.txid}`);
            if (setThreshold_2Of_3Result.txid) txIds.push(["UpdateKeyPage", setThreshold_2Of_3Result.txid]);
        } else {
            console.log(`UpdateKeyPage FAILED: ${setThreshold_2Of_3Result.error}`);
        }


        // =========================================================
        // Raise Threshold to 3 (2-of-3 signatures) (Action: CoSign — update_key_page under an M-of-N threshold)
        // =========================================================
        // A threshold needs DISTINCT keys signing the SAME transaction. Signing the
        // body twice does not work: the first signature's metadata becomes the
        // transaction's `initiator` and is baked into the header, so a second
        // independent signature is over a different transaction hash and neither
        // copy reaches the threshold. Co-sign the existing envelope instead.
        const raiseThresholdTo_3_2Of_3SignaturesBody = TxBody.updateKeyPageSetThreshold(3);
        const raiseThresholdTo_3_2Of_3SignaturesSigner = new SmartSigner(client, generateKeysSigner_1Kp.toKey(), `${createAdiUrl}/multisig-book/1`);
        let raiseThresholdTo_3_2Of_3SignaturesEnvelope = (await raiseThresholdTo_3_2Of_3SignaturesSigner.sign(`${createAdiUrl}/multisig-book/1`, raiseThresholdTo_3_2Of_3SignaturesBody)).envelope;
        // Co-signer 0: appends a signature to the SAME transaction hash.
        raiseThresholdTo_3_2Of_3SignaturesEnvelope = await new SmartSigner(client, generateKeysSigner_2Kp.toKey(), `${createAdiUrl}/multisig-book/1`)
            .signExisting(raiseThresholdTo_3_2Of_3SignaturesEnvelope);
        // Submit only once every signature is collected: resubmitting a signature
        // that is already on chain trips replay protection.
        // execute() throws on a rejected envelope, so reaching the next line means
        // the network accepted it.
        // execute() serialises the Envelope itself — passing asObject() here would
        // hand it a plain object it cannot re-serialise.
        const raiseThresholdTo_3_2Of_3SignaturesResult = await client.v2.execute(raiseThresholdTo_3_2Of_3SignaturesEnvelope);
        const raiseThresholdTo_3_2Of_3SignaturesTxid = raiseThresholdTo_3_2Of_3SignaturesResult.txid.toString();
        // Acceptance is not execution. A transaction that has not reached its
        // threshold is accepted and then sits pending, so the only honest
        // confirmation is the delivered status.
        let raiseThresholdTo_3_2Of_3SignaturesStatus = 'unknown';
        for (let i = 0; i < 30; i++) {
            try {
                const { status } = await client.v2.queryTx(raiseThresholdTo_3_2Of_3SignaturesTxid);
                raiseThresholdTo_3_2Of_3SignaturesStatus = status?.code ?? 'unknown';
                if (raiseThresholdTo_3_2Of_3SignaturesStatus !== 'pending' && raiseThresholdTo_3_2Of_3SignaturesStatus !== 'remote') break;
            } catch { /* not indexed yet */ }
            await new Promise((r) => setTimeout(r, 2000));
        }
        if (raiseThresholdTo_3_2Of_3SignaturesStatus === 'delivered') {
            console.log(`CoSign update_key_page DELIVERED with 2 signature(s) - TxID: ${raiseThresholdTo_3_2Of_3SignaturesTxid}`);
        } else {
            console.log(`CoSign update_key_page NOT DELIVERED (status=${raiseThresholdTo_3_2Of_3SignaturesStatus}) - TxID: ${raiseThresholdTo_3_2Of_3SignaturesTxid}`);
        }


        console.log("\n========== Transaction Summary ==========");
        for (const [label, txid] of txIds) {
            console.log(`  ${label}: ${txid}`);
        }
        console.log("Flow completed successfully!");
    } catch (err) {
        console.error("Flow failed:", err);
    }
}

main().catch(console.error);
